sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "12.18.1"
before_install:
  - npm install -g npm@latest
install:
  - npm install
before_script: 
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
